# Generated by Django 3.0.3 on 2020-04-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restraurant',
            new_name='Restaurant',
        ),
    ]
