# Generated by Django 3.0.3 on 2020-04-13 21:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200411_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('favourite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Favourite')),
            ],
        ),
        migrations.RenameModel(
            old_name='Deals',
            new_name='Deal',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitdue/latitude'),
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
