# Generated by Django 3.0.3 on 2020-04-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200413_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Toronto', max_length=100),
        ),
    ]
