# Generated by Django 3.0.3 on 2020-04-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_restaurant_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Likes',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
