# Generated by Django 3.0.3 on 2020-04-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200415_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='restraurant',
            new_name='restaurant',
        ),
    ]
